### ISSUE TITLE
Unable to add a style

### ISSUE THREAD

**Issue by MulverineX** [VChet/StyleBase#1]
https://github.com/MulverineX/legacy-settings-icons
`legacy-settings-icons.user.css`

(the prompt just gives me [object Object])

**Comment by VChet** [comment]
Thank you for your report!
The error occurs because your repository default branch is named **main** instead of **master**. No need to change anything on your side, I'll fix the parser to check the repository's  `default_branch` field first. The error message will be fixed too.

**Comment by VChet** [comment]
6d4194290ddc6265070f75975134ea5035449ade
