### ISSUE TITLE
Editing styles acting weird

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#12]
I've tried to edit my Twitter For Mastodon theme to add a thumbnail image, I've pasted in the link, pressed 'Edit', and, it's changed the thumbnail, but it now has the name and description of another theme??? I haven't touched the name & description fields, all I did was change the image.
This kind of thing also happened when I tried to edit my other styles.
![](https://i.imgur.com/X6VDdK5.png)

Not sure how else to explain it. But it is incredibly annoying

**Comment by RiedleroD** [comment]
Happened to me too, it was the staging version, so I didn't think much of it at the time, but it seems as if it's still an issue.

**Comment by VChet** [comment]
Should be fixed in [3.2.0](https://github.com/VChet/StyleBase/releases/tag/v3.2.0)
