### ISSUE TITLE
Very Minor: Clicking the StyleBase logo in the header should reset all filters

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#13]
VERY minor thing, but I was confused when clicking the logo didn't take me back home, as that's what most sites do when you click the header. 

When I say resetting filters I mean basically the same function as clicking this X that's barely noticeable:
![](https://i.imgur.com/UF8fUpA.png)

**Comment by RiedleroD** [comment]
omg I didn't even know that x is present XD
another thing to fix I guess

**Comment by VChet** [comment]
[3.2.1](https://github.com/VChet/StyleBase/releases/tag/v3.2.1)
