### ISSUE TITLE
Use own rating system instead of Github's / Codeberg's

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#14]
Since you're now able to add styles from the same repository, those styles will share the amount of stars it has gained. This can become an issue for example when sorting by Most Liked and the same author is shown multiple times due to their themes sharing the same amount of stars on their repo.

**Comment by RiedleroD** [comment]
Damn you beat me to it.

Anyway, I suggest a star rating system, like youtube used to have in ye olden days. I think that will reflect the quality of a style the best.

**Comment by VChet** [comment]
Will not be added. Definitely not anytime soon.
1. Adding your own rating system will require additional verification to exclude the possibility of cheating. This will take time to implement, which can be spent on something else.
1. It is possible to link the rating to the GitHub account, but a very small number of users are authorized with their accounts. Even if unregistered users will be allowed to use it, their number is still too small and most styles will have zero-rating
1. This proposal is at odds with my original idea of ​​promoting styles via GitHub stars. That is, if someone wants to increase the rating, then he has to star the repository. As well that's one of the reasons why StyleBase has no comments. If some user wants to thank a style author/report a bug - he should do it at the original repository.

Having multiple styles with the same rating is an issue but not a critical one, more like a minor inconvenience.

**Comment by Freeplayg** [comment]
Maybe instead of Most Liked Styles, you can have Most Liked Authors instead? Then the user would click on their profile to see their styles, sort of acting like categories

**Comment by VChet** [comment]
I will think about what can be done in the near future.
In the long term, I plan to make a separate page for style creators, which will include the overall rating of the author, his organizations, a list of all his styles, the ability to edit several styles on one page. Once this will be done, it will be easier to collect and sort styles by author rating.
