### ISSUE TITLE
Sometimes doesn't filter when going directly to a user's page

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#16]
Sometimes when I open a link to for example https://stylebase.cc/Freeplay, it doesn't filter to show styles _only_ from me.
Refreshing the page fixes it

![](https://i.imgur.com/gQkPxob.png)

**Comment by VChet** [comment]
Thanks for the report!
Should be fixed in [3.5.0](https://github.com/VChet/StyleBase/releases/tag/v3.5.0)
