### ISSUE TITLE
overview: style card star count clashes with update time if either is too long

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#18]
context: I have a pretty small display, so I might be the only one that cares, but it currently looks like [this](https://riedler.wien/sfto/screenshot_archive/stylebase_eugh.png).

Since that's kinda ugly and hard to read, I have already made a solution (in raw css because I can't do js, sorry, no PR for you today):

You have to set `margin-right:0.75em` (or more or less, idc) to the star `<span>` and `flex-wrap:wrap;` to the `<div>` it's in.

[Here](https://riedler.wien/sfto/screenshot_archive/stylebase_fixed.png)'s a screenshot of how that looks.

**Comment by VChet** [comment]
How about replacing the text with emojis?
![image](https://user-images.githubusercontent.com/17050347/103924487-e90e1f00-5137-11eb-8bc9-9597e6e94b27.png)![image](https://user-images.githubusercontent.com/17050347/103924920-9719c900-5138-11eb-9fbb-7439fc409c14.png)

**Comment by RiedleroD** [comment]
That's also a great idea (definitely implement that), but someone somewhere (who has a tiny screen with a huge font) will still have the issue I had, which means adding my proposed solution along with emojis would probably be best.

**Comment by VChet** [comment]
Fixed in [4.0.1](https://github.com/VChet/StyleBase/releases/tag/v4.0.1)
