### ISSUE TITLE
[Feature Request] Allow manually setting details

### ISSUE THREAD

**Issue by MulverineX** [VChet/StyleBase#2]
When adding a theme, you should be able to manually set the theme title & the path to the preview image.

**Comment by MulverineX** [comment]
Also if you add this please remove my settings icons theme from the site so I can readd it

**Comment by MulverineX** [comment]
Thanks for the speedy reply, excited for improvements to the system. Also thank you for the info on how it looks for the preview image. The biggest part for me is the title since I don't want discord in the repo name but that's important for a generic styles site.

**Comment by VChet** [comment]
724dce320dba05742acc212653c9a3f6c4dd9b79
