### ISSUE TITLE
Question: What happens when people sign up with the same username from GitHub & Codeberg?

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#20]

**Comment by VChet** [comment]
Usernames can be non-unique. The accounts will not be linked in any way. Depending on the authorization method, the githubId or codebergId field is saved in the User model.

**Comment by Freeplayg** [comment]
What about in links like https://stylebase.cc/user/Freeplay ? Which one would it go to

**Comment by VChet** [comment]
Links like this one will filter styles by the owner username. So styles from both accounts will be included.
It will be fixed when new user pages will be done, where styles will be connected directly to profiles.
