### ISSUE TITLE
improve keyword search

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#21]
I kinda have the problem where when I search for "wiki" (without quotes), the wikipedia styles don't show up because its searching for the full term. Maybe you could implement a searching algorithm that just searches if the search term is present as a substring instead of a word? And also maybe implement a google-esque search engine, including quoting stuff for exact matches, prepending dashes for excluding stuff and similar stuff. I'm sure you can solve this problem.

**Comment by VChet** [comment]
Search by substring added in [4.3.0](https://github.com/VChet/StyleBase/releases/tag/v4.3.0).
I'll think about adding more search parameters if search results will be too irrelevant.
