### ISSUE TITLE
I can't open styles while logged in?

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#23]
I can't open any styles after logging in with my github account. The scrollbar gets locked & the url is being changed, but the userstyle card doesn't show. After logging out, it worked again, but after loggin in again, it didn't.

**Comment by VChet** [comment]
Thanks for the report, but I can't reproduce it. Could you please write the browser (and version) you are using and test it using other browsers, if possible?
Also, could try opening the devtools (press F12) and check if there any errors in the console output?

**Comment by RiedleroD** [comment]
Firefox 85.0.2
![20210214_19h47m12s_grim](https://user-images.githubusercontent.com/57227431/107886001-9d505180-6efd-11eb-8d4b-4bce7b2d00f5.png)
Google Chrome 88.0.4324.150
![20210214_19h54m12s_grim](https://user-images.githubusercontent.com/57227431/107886184-937b1e00-6efe-11eb-9c3e-aa5e1c2ecf58.png)
As far as I can tell, it's the same behaviour with different error messages, though I'm not an expert on this subject. Maybe it's a problem on my end?

**Comment by VChet** [comment]
I think I found the cause of the error. The problem is not on your side and should be fixed now, please try again

**Comment by RiedleroD** [comment]
👍🏻 works as expected again
