### ISSUE TITLE
Unable to add styles with `user.styl` file extension

### ISSUE THREAD

**Issue by AbhayAysola** [VChet/StyleBase#3]
Hi, I've just found out about stylebase.cc and I wanted to add a style of my own, but I can't add a style with the `user.styl` extension. Please add support for it. Thanks

**Comment by VChet** [comment]
Thanks for the feedback! Support will be added soon

**Comment by VChet** [comment]
f7dd9aa5043b0baedb3074d70dccf599ad8f44f6
