### ISSUE TITLE
Adding multiple styles from a single repository

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#4]
I'd really like to add every file as a seperate style, because I currently have all of my styles in https://github.com/RiedleroD/userstyles-riedler/, with the master branch serving as a kind of stable release hub, and the seperate branches as development versions.

So I'd really like to be able to just add a file or a branch and call it a day.

**Comment by VChet** [comment]
Thanks for your feedback!
At the moment, all logic is based on the principle of one style - one repository. I'll see what can be done with this, but it will take a while. Most likely I'll make it possible to choose which file to add as a new style in the 'Add style' popup

**Comment by RiedleroD** [comment]
Thank you, man. We've waited so long for a proper userstyle host and you're doing just that!

**Comment by VChet** [comment]
Available now on https://staging.stylebase.cc. It still needs more testing and polishing, but file selection works, and I haven't encountered critical bugs while testing.

**Comment by RiedleroD** [comment]
idk why but I've gotten a 11000:Mongoerror.

Steps to reproduce:
- parse https://github.com/RiedleroD/userstyles-riedler
- add dark grimm.user.css

What I think the error is:
~~the filenames don't get escaped properly which makes mongodb lose its shit when it sees the whitespace.~~
This may not be the case because I can't add any other styles from this repo. I can only add one style from this repo at a time which leads me to believe the repo link is still used somewhere in the identification and/or storaging process.

**Comment by VChet** [comment]
oops, I forgot to update the index in this database. It was disallowed to add non-unique repo URLs. Should be okay now

**Comment by RiedleroD** [comment]
aye, thanks. It works perfectly now.

**Comment by VChet** [comment]
Implemented in [3.0.0](https://github.com/VChet/StyleBase/releases/tag/v3.0.0)
