### ISSUE TITLE
Custom style description

### ISSUE THREAD

**Issue by RiedleroD** [VChet/StyleBase#7]
For some styles, a description would be needed. For example: I have a style (Darklearning) which technically is a style for the moodle system, but is specifically for the moodle platform that our school uses. So it'd be nice if I could tell people that this is a style that isn't really applicable if they're not going to the TGM.

Also, a summary of what the style does, what the style doesn't and what the style will do in the future would be nice to being able to include.

**Comment by VChet** [comment]
Style description is being taken from the repository description. So if you need to change it - change it in a repository.

I suppose you meant different descriptions for styles from a single repository (#4). If that's so, I'll add a field for it, the same way how custom name and custom preview works.

A little reminder that parser still has no information on usercss file contents and I can't take the description from it. Parsing of usercss metadata is in long term plans

**Comment by RiedleroD** [comment]
Well I didn't know there was a description at all, but yeah. If you already have a field for the description, then just making it editable would probably be the best.

**Comment by VChet** [comment]
Implemented in [3.0.0](https://github.com/VChet/StyleBase/releases/tag/v3.0.0)
