### ISSUE TITLE
Add support for Gitea

### ISSUE THREAD

**Issue by Freeplayg** [VChet/StyleBase#9]
[This is what Gitea is](https://gitea.io)

Since it is self-hosted, they'll have different URL's. 
So for Usernames, you could have something like @Username@DomainURL like how Decentralized Social Media does it (Mastodon, Pleroma, Friendica, etc.)

I currently host all of my themes on https://codeberg.org/ (which uses Gitea), so it would be nice to be able to use that instead of having to do something like Mirroring all of my repo's to GitHub

**Comment by VChet** [comment]
I haven't worked with Gitea and its API, but at first glance, API seems identical to GitHub. I'll try to parse repositories from there, and if it won't be needed to write a completely new parser - support will be added in the near future

**Comment by VChet** [comment]
Implemented in [3.1.0](https://github.com/VChet/StyleBase/releases/tag/v3.1.0)
